name: kitti
disp_name: kitti_eigen_test_full
dir: /high_perf_store/ad-prediction/wjy/forecast/idea/tmp/data/
filenames: data_split/kitti/eigen_test_files_with_gt.txt
kitti_bm_crop: true
valid_mask_crop: eigen